+++
title = "never"
author = ["Yasuhito Takamiya"]
date = 2021-03-18T00:00:00+09:00
draft = false
+++

[SRS の回答方式による効果の違い]({{< relref "20210319113717-srs_の回答方式による効果の違い" >}})を確認するために、[Execute Program]({{< relref "20210302155222-execute_program" >}}) のレッスン [never](https://www.executeprogram.com/courses/typescript/lessons/never) を元に Anki カードを起こしてみる。作った Anki カードはこのノートの一番下にある。

---


## never の説明 {#never-の説明}

関数の中には、決して戻らないものがあります。例えば、常に例外を投げる関数は決して戻りません。

```typescript
// この関数は戻らない
function throws() {
  throw new Error('oh no');
}
```

この関数の戻り値の型はどうすればよいでしょうか？ TypeScript は、この関数の戻り値の型を `void` と推論します。しかし、それではコードで何が起こっているのかをコンパイラは完全には把握できていません。

`void` 型は、何らかの処理を行い終了するが、値を返さない関数のための型です。上の関数はこれとは異なり、この関数を呼び出しても、その後のコードは全く実行されません。

幸いなことに、TypeScript にはそのための型があります: `never` です。

```typescript
// 戻らない関数の返り値は never と指定する
function throws(): never {
  throw new Error('oh no');
}
```

`never` 型はちょっと不思議です。他のどの型にも割り当て可能です[^fn:1]。例えば、 `number` 型の変数に割り当てることができます (ただし、実行すると例外が投げられます)。

```typescript
function throws(): never {
  throw new Error('oh no');
}
// never はどんな型にも割り当てられる
const n: number = throws();

// → Error: oh no
```

最初は、 `never` が `any` のように振る舞っているように見えます。なぜなら、 `never` を `number` （または `string` 、その他何でも）に割り当てることができるからです。しかし、 `any` と違って、これは安全です。

コンパイラは `throws` 関数が決して戻らないことを知っているので、変数 `n` には何も代入されないことも知っています。型は実行時にデータが正しいことを保証するために存在します。もし、実行時に代入が実際に行われることがなく、コンパイラが事前にそのことを確実に知っているのであれば、 `never` を代入する変数の型は重要ではありません。

しかし、 `never` に他の型を割り当てることはできません。そうすると、 `never` のルールである「実際に値を保持することはない」を破ってしまいます。 `never` に何らかの値を代入しようとすると、常に型エラーになります。

```typescript
// never には何も割り当てられない
const aNever: never = 5;

// → type error: Type 'number' is not assignable to type 'never'.
```

絶対に `never` には何も割り当てられません。 `any` ですらも!

```typescript
const anAny: any = 5;
// never には any ですら割り当てられない
const aNever: never = anAny;

// → type error: Type 'any' is not assignable to type 'never'.
```

関数が常に例外をスローするが、明示的な戻り値の型を持たない場合、TypeScript は戻り値の型を `void` と推論します。これは悪いことではありませんが、明示的に `never` とマークしたほうが、TypeScript にもう少し多くの情報を与えることができます。

例えば、ある関数が `never` を返す別の関数を呼び出したとします。TypeScript は外側の関数の型も `never` と正しく推論します。

```typescript
function throws(): never {
  throw new Error('oh no');
}

// この戻り値の型は never と推論される
function alsoThrows() {
  return throws();
}

// never は number に割り当てることができる
const n: number = alsoThrows();
```

このコードがコンパイルされたことで、 `alsoThrows` の戻り値の型が `never` であることがわかりました。もし戻り値の型が `void` であれば、数値に割り当てることはできません。

次の関数の戻り値の型を `never` に変更するとどうなるでしょうか。結果は型エラーが発生します。なぜなら、この関数は戻るからです。TypeScript は `never` 関数が値を返すことを許可しません。

```typescript
function f(): number {
  return 5;
}
```

戻り値を `never` に変更すると:

```typescript
function f(): never {
  return 5;
}

// → type error: Type 'number' is not assignable to type 'never'.
```

TypeScript では、 `never` 関数が条件付きで戻ることもできません（例: `if` の中）。関数が値を返す方法があるならば、その戻り値の型は `never` であってはならないのです。(この関数は型エラーを発生させます)

```typescript
function forcePositive(x: number): never {
  if (x > 0) {
    // 型エラー
    return x;
  } else {
    throw new Error('Number was negative!');
  }
}

// → type error: Type 'number' is not assignable to type 'never'.
```

`never` 型が適用されるのは、例外を発生させる関数だけではありません。例えば、無限ループを持つ関数は、 `never` 型の戻り値を持つことができます（そうすべきです！）。

残念ながら、ここではその動く実例を示すことはできません。なぜなら、それは決して終了しないからです。しかし、その逆の例を示すことはできます。つまり、無限ループのように見える関数で、絶対に終わらないと主張していますが、時々戻ってくることがあるようなものです。これは型エラーです。

```typescript
function f(): never {
  while (true) {
    // 型エラー
    if (Math.random() < 0.000001) {
      break;
    }
  }
}

// → type error: A function returning 'never' cannot have a reachable end point.
```

`never` 型の代表的なユースケースとして網羅性チェックがあります。到達不能な部分で `never` を返す関数を呼び出すことで、実行時エラーをチェックできます。

```typescript
function fail(message: string): never { throw new Error(message); }

function foo(x: string | number): boolean {
  if (typeof x === "string") {
    return true;
  } else if (typeof x === "number") {
    return false;
  }

  // never 型のない言語では、次のいずれかでエラーになる
  // - すべてのコードパスで値を返していない (厳密な null チェック)
  // - または、到達不能コードの検出
  // しかし TypeScript は fail 関数が never を返すことを知っているので、
  // プログラマは実行時の安全性/網羅性チェックのために fail を呼び出すことができる
  return fail("Unexhaustive!");
}
```

最後に、 `void` と `never` について簡単にまとめておきます。

`void` は、関数が最終的に終了して戻ることを意味します。単に、何の値も返さないということです。関数には `return` 文がないか、または `return` 文の後に値がない状態になっています。 `void` 型は、値がないことを表すので、何にも代入できません。

`never` は、関数が決して正常に終了しないことを意味します。例外が発生したり、無限ループに陥ったりするかもしれません。Node のようなサーバーサイドのシステムであれば、 `process.exit()` を呼び出してプロセスを終了させるかもしれません。いずれにしても、実行が関数の最後に到達することはありません。 `never` 型は何にでも代入可能です。なぜならコンパイラは、実行時には実際には代入が行われないことを知っているからです。


## Anki カード {#anki-カード}


### never 型の戻り値 {#never-型の戻り値}


#### Text {#text}

次のような常に例外を投げる関数の戻り値の型は {{c1::never}} と指定できる

```typescript
function throws() {
  throw new Error('oh no');
}
```


#### Extra {#extra}

```typescript
function throws(): never {
  throw new Error('oh no');
}
```


### ボトム型 {#ボトム型}


#### Text {#text}

{{c1::never}} はすべての型の{{c2::サブタイプ (派生型)}} であり、これを{{c3::ボトム型 (bottom type)}} と呼ぶ


#### Extra {#extra}


### never への代入 {#never-への代入}


#### Front {#front}

never 型の変数に値を代入しようとすると、何が起こるか？

```typescript
const aNever: never = 5;
```


#### Back {#back}

型エラー

```typescript
const aNever: never = 5;
// → type error: Type 'number' is not assignable to type 'never'.
```


### never への any の代入 {#never-への-any-の代入}


#### Front {#front}

`never` 型の変数に `any` 型の値を代入しようとすると何が起こるか？

```typescript
const anAny: any = 5;
const aNever: never = anAny;
```


#### Back {#back}

型エラー

```typescript
const anAny: any = 5;
const aNever: never = anAny;

// → type error: Type 'any' is not assignable to type 'never'.
```

[^fn:1]: `never` はすべての型のサブタイプ (派生型) であり、これをボトム型 (bottom type) と呼ぶ。つまり、他のすべての型に割り当てることができ、 `never` 型の値はどこでも安全に使えるという意味である。理論的な意味としては、ボトム型は値を持たない型としてとらえることができ、常に偽である数学的命題に相当する。
